version: '2'
services:
  fusiondirectory:
    # image: clubcedille/debian-fusiondirectory:latest
    build: .
    restart: on-failure:5
    environment:
      - "LDAP_SERVER=ldap"
    depends_on:
      - ldap
    ports:
      - "10080:10080"
    extends:
      service: ldap-variables
      file: config/compose-variable.yml

  ldap:
    # image: clubcedille/debian-ldap:latest
    build: ../ldap
    restart: on-failure:1
    volumes:
    - /srv/ldap/var/lib/ldap:/var/lib/ldap:rw
    - /srv/ldap/etc/ldap/slapd.d:/etc/ldap/slapd.d:rw
    ports:
      - "389:389"
    extends:
      service: ldap-variables
      file: config/compose-variable.yml

  keycloak:
    image: jboss/keycloak
    # build: ../ldap
    restart: on-failure:1
    extends:
      service: ldap-variables
      file: config/compose-variable.yml
    ports:
    - 8080:8080
    environment:
    - "LDAP_SERVER=ldap"
    - "KEYCLOAK_USER=admin"
    - "KEYCLOAK_PASSWORD=admin"

  # web:
  #   image: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   links:
  #   - app
  #   volumes_from:
  #   - app
  #   environment:
  #   - VIRTUAL_HOST
  # app:
  #   image: indiehosters/nextcloud
  #   links:
  #   - db
  #   volumes:
  #   - ./data/apps:/var/www/html/apps
  #   - ./data/config:/var/www/html/config
  #   - ./data/data:/var/www/html/data
  # db:
  #   image: mysql
  #   volumes:
  #   - ./mysql/runtime:/var/lib/mysql
  #   environment:
  #   - MYSQL_ROOT_PASSWORD
