version: '2'
services:
  fusiondirectory:
    image: clubcedille/debian-fusiondirectory:latest
    # build: .
    restart: on-failure:5
    environment:
      - "LDAP_SERVER=ldap"
    depends_on:
      - ldap
    ports:
      - "10080:10080"
    extends:
      service: ldap-variables
      file: config/compose-variable.yml

  ldap:
    image: clubcedille/debian-ldap:latest
    # build: ../ldap
    restart: on-failure:1
    volumes:
    - /srv/ldap/var/lib/ldap:/var/lib/ldap:rw
    - /srv/ldap/etc/ldap/slapd.d:/etc/ldap/slapd.d:rw
    ports:
      - "389:389"
    extends:
      service: ldap-variables
      file: config/compose-variable.yml
