version: "2"
services:
  ldap-variables:
    environment:
    - "SLDAP_ROOTPASS=toor"
    - "SLDAP_ORGANISATION=Acme Widgets Inc."
    - "SLDAP_DOMAIN=example.com"
    - "FUSIONDIRECTORY_PASSWORD=toor2"
    - "ENABLE_SSL=0"
